### ISSUE TITLE
Combine the OLD meeting page (.MD) and the new meetings page 

### ISSUE THREAD

**Issue by RDominguezFL** [JaxLUG/jaxlug.github.io#4]
Why is the JaxLUG group  no longer making progress in this repo?  

Sad.

**Comment by wltjr** [comment]
This was an experiment to see about moving to like decentralized and non hosted website, so if any members came and went, the website/wiki hosting was not impacted. But like many things, there just wasn't the efforts from others to keep it going. I have done to much, long ago was accused it being my lug, so ever since then, I have let others do more or less.

You are welcome to champion the effort, I will reach out to you, or you can to me, on discord or email for a direct conversation.

**Comment by RDominguezFL** [comment]
i have tries to answer your friend request in Discord but i keep getting  logged out.  maybe is my security settings or something.  but  this weeks JaxLug meeting im presenting an attempt to make a collab in GitHub.  i was hopping to use your repo but was unable to reach you till today.  So i ended up utilizing  Ralph's Figuroa repo.  //thegreatplace/JaxLUG.  i would rather like to manage this repo because is almost empty  and has no other repositories attached.

**Comment by RDominguezFL** [comment]
Any way  the presentation  is already written  with the other repository in mind.   Maybe i can migrate to this one eventually.  But first  i have to see if the "collab"  actually takes off.   Then we can make the announcement to migration.

**Comment by RDominguezFL** [comment]
im going to sign-off this issue  we have already started the collab
